server:
  port: 8181

spring:
  application:
    name: video-raccoon

zoneminder:
  base-url: http://localhost:8180/zm

go2rtc:
  base-url: http://localhost:1984

client:
  allowed-origins:
    - http://localhost:4300
